// skills
export const SKILLS_DATA = [
  {
    title: "Markup",
    items: [
      "HTML5",
      "CSS3",
      "SCSS",
      "웹 표준",
      "웹 접근성",
      "UI 가이드 & 구조 설계",
    ],
  },
  {
    title: "Interaction",
    items: [
      "JavaScript(ES6)",
      "jQuery",
      "공통 함수 모듈화",
      "UI 인터랙션 구현",
    ],
  },
  {
    title: "Workflow",
    items: [
      "Git",
      "Figma",
      "Adobe XD",
      "Photoshop",
      "Salesforce",
      "Veeva / IQVIA",
      "React(학습)",
    ],
  },
];

// history
export const HISTORY_DATA = [
  {
    period: "2021.01 – 2024.06",
    duration: "3년 6개월",
    company: "이노부스트",
    role: "퍼블리셔 / 파트 리더",
    desc: ["퍼블리싱 파트 리딩 및 구조·표준화 중심 실무 수행"],
  },
  {
    period: "2015.09 – 2020.03",
    duration: "4년 7개월",
    company: "아이뱅크 디지털웍스",
    role: "퍼블리셔",
    desc: ["이커머스·글로벌 사이트 구축 및 운영 중심 퍼블리싱"],
  },
  {
    period: "2014.08 – 2015.06",
    duration: "11개월",
    company: "나우온플레이",
    role: "퍼블리셔",
    desc: ["브랜드 사이트 구축 및 프로모션 콘텐츠 퍼블리싱"],
  },
  {
    period: "2012.10 – 2013.10",
    duration: "1년 1개월",
    company: "블루웹",
    role: "디자이너",
    desc: ["디자인부터 퍼블리싱까지 전 과정 실무 경험"],
  },
];

// works
const IMAGE_BASE_PATH = `${import.meta.env.BASE_URL}images/`;
const getImagePath = (id, type = "main") => {
  return type === "main"
    ? `${IMAGE_BASE_PATH}work_${id}.png`
    : `${IMAGE_BASE_PATH}work_${id}_modal`;
};

export const WORKS_DATA = [
  {
    id: 15,
    title: "사내 관리자 플랫폼",
    desc: "Bootstrap 기반 관리자 UI 리뉴얼 및 구조 개선",
    keyFeatures: [
      "Bootstrap 기반 기존 구조 리뉴얼 및 HTML/SCSS 템플릿 공통화",
      "사내 관리자 UI 일관성 유지를 위한 스타일 가이드 제작",
      "유지보수성과 확장성을 고려한 관리자 UI 구조 개선",
    ],
    role: "퍼블리싱 100%",
    year: "2023-2024",
    device: "PC / Mobile",
    category: "Admin Platform",
    subImgCount: 3,
    link: "",
  },
  {
    id: 14,
    title: "사내 인사평가 시스템",
    desc: "사내 인사평가 프로세스를 반영한 반응형 웹 시스템 구축",
    role: "퍼블리싱 100%",
    year: "2023",
    device: "Responsive",
    category: "Web System",
    link: "",
  },
  {
    id: 13,
    title: "길리어드 HIVISION 사이트",
    desc: "신규 반응형 웹사이트 구축 및 운영",
    keyFeatures: [
      "반응형 환경에서 콘텐츠 슬라이드 및 인터랙션 UI 구현",
      "퀴즈 및 다량 콘텐츠 운영을 고려한 마크업 구조 설계",
    ],
    role: "퍼블리싱 100%",
    year: "2023",
    device: "Responsive",
    category: "Brand Site",
    subImgCount: 3,
    link: "https://www.hi-vision.co.kr/web",
  },
  {
    id: 12,
    title: "Veeva · IQVIA CLM 콘텐츠",
    desc: "제약사 iPad 환경에 최적화된 세일즈 콘텐츠 구축",
    keyFeatures: [
      "iPad 전용 해상도 및 터치 환경을 고려한 콘텐츠 구현",
      "Salesforce CRM 연계 메디컬 세일즈 콘텐츠 제작",
      "Veeva CLM · IQVIA CLM 플랫폼 가이드에 맞춘 콘텐츠 구축",
    ],
    role: "퍼블리싱 100%",
    year: "2021-2024",
    device: "Tablet (iPad)",
    category: "Digital Content",
    subImgCount: 1,
    link: "",
  },
  {
    id: 11,
    title: "노보 노디스크 카카오톡 채널",
    desc: "카카오톡 인앱 브라우저 환경 콘텐츠 구축 및 운영",
    keyFeatures: [
      "카카오톡 인앱 환경 제약을 고려한 모바일 전용 UI 퍼블리싱",
      "인앱 브라우저 환경에서의 콘텐츠 운영 및 유지보수",
    ],
    role: "퍼블리싱 100%",
    year: "2021-2024",
    device: "Mobile",
    category: "SNS Channel",
    subImgCount: 2,
    link: "",
  },
  {
    id: 10,
    title: "제이시스메디컬 닥터자스민 사이트",
    desc: "서비스 사용자 화면 웹사이트 구축",
    keyFeatures: [
      "Zoom 화상회의 연계를 고려한 화면 영역 구성 및 UI 퍼블리싱",
      "화상 환경에 맞춘 채팅 영역 UI 퍼블리싱",
      "디바이스 환경에 따라 레이아웃이 유연하게 대응되는 적응형 UI 구현",
    ],
    role: "퍼블리싱 100%",
    year: "2021",
    device: "PC / Mobile",
    category: "Service Site",
    subImgCount: 2,
    link: "",
  },
  {
    id: 9,
    title: "한국산텐제약 알레지온 사이트",
    desc: "제약사 사이트 구축 및 운영",
    role: "퍼블리싱 100%",
    year: "2021-2022",
    device: "PC / Mobile",
    category: "Brand Site",
    subImgCount: 2,
    link: "",
  },
  {
    id: 8,
    title: "아모레퍼시픽 뉴스스퀘어",
    desc: "사내 그룹 사이트 리뉴얼",
    role: "퍼블리싱 70% / PL",
    year: "2019/11-2020/03",
    device: "Responsive",
    category: "Groupware",
    link: "",
  },
  {
    id: 7,
    title: "이니스프리 글로벌 사이트",
    desc: "글로벌 사이트 운영 및 유지보수",
    keyFeatures: [
      "11개국 글로벌 사이트 콘텐츠 운영",
      "이벤트 페이지 및 EDM 콘텐츠 퍼블리싱",
    ],
    role: "운영 리드",
    year: "2018/04-2019/10",
    device: "Responsive",
    category: "Brand Mall / EDM",
    link: "",
  },
  {
    id: 6,
    title: "이니스프리 국문 온라인 쇼핑몰 MC 운영",
    desc: "국문 온라인 쇼핑몰 이벤트 운영",
    keyFeatures: [
      "신제품 론칭 이벤트 및 프로모션 페이지 제작",
      "마이크로 사이트 형태의 이벤트 콘텐츠 운영",
    ],
    role: "운영 전담",
    year: "2016/09-2018/03",
    device: "PC / Mobile",
    category: "E-Commerce / Promotion",
    link: "",
  },
  {
    id: 5,
    title: "이니스프리 국문 온라인 쇼핑몰 리뉴얼",
    desc: "국문 온라인 쇼핑몰 리뉴얼 프로젝트 참여",
    keyFeatures: [
      "제품 상세페이지 중심 퍼블리싱",
      "서브페이지 퍼블리싱 일부 담당",
    ],
    role: "퍼블리싱 30% 참여",
    year: "2016/02-2016/09",
    device: "PC / Mobile",
    category: "E-Commerce",
    link: "",
  },
  {
    id: 4,
    title: "이니스프리 모음재단",
    desc: "모음재단 사이트 리뉴얼",
    role: "퍼블리싱 100%",
    year: "2015/11-2015/12",
    device: "Responsive",
    category: "Brand Foundation",
    link: "",
  },
  {
    id: 3,
    title: "아리따움 온라인몰",
    desc: "국문 온라인 쇼핑몰 신규 구축 프로젝트",
    keyFeatures: ["PC 환경 서브페이지 퍼블리싱"],
    role: "퍼블리싱 30% 참여",
    year: "2015/09-2015/11",
    device: "PC / Mobile",
    category: "E-Commerce",
    link: "",
  },
  {
    id: 2,
    title: "쉐라톤 워커힐 호텔",
    desc: "호텔 모바일 사이트 리뉴얼",
    role: "퍼블리싱 100%",
    year: "2015/01-2015/02",
    device: "Mobile",
    category: "Brand Site",
    link: "",
  },
  {
    id: 1,
    title: "신세계 면세점 온라인몰",
    desc: "국문/중문 사이트 운영 및 국문 PC 메인 리뉴얼",
    keyFeatures: [
      "국문/중문 사이트 콘텐츠 운영",
      "국문 PC 메인 페이지 리뉴얼",
      "프로모션 EDM 콘텐츠 퍼블리싱",
    ],
    role: "퍼블리싱 리뉴얼 100% / 운영 전담",
    year: "2014/08-2015/06",
    device: "PC / Mobile",
    category: "E-Commerce / EDM",
    link: "",
  },
].map((item) => ({
  ...item,
  img: getImagePath(item.id, "main"),
  modalBaseImg: getImagePath(item.id, "modal"),
}));
